### ISSUE TITLE
Navigation in sign in screen

### ISSUE THREAD

**Issue by Ashish145** [googledrive/ios-quickeditor#2]
How can i put navigation bar in google login screen?

Because if user don't want to sign in then there is no way to go back to the previous screen user must need to kill the application.

Thanks

![ios simulator screen shot jul 11 2015 11 16 31 am](https://cloud.githubusercontent.com/assets/13284793/8632561/4e155e94-27be-11e5-9ad4-385459dd38fb.png)

**Comment by SzabZappDesigntemplates** [comment]
You could embed it in a navigation viewController, but then when you hit the back button you will get something like this:

2015-07-17 11:13:27.351 treevApp[23468:7958719] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSInvocation _invocationWithMethodSignature:frame:]: method signature argument cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f0f8c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010ea39bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010efc42b0 -[NSMethodSignature frameLength] + 0
	3   treevApp                            0x000000010c6eb97c -[GTMOAuth2ViewControllerTouch signIn:finishedWithAuth:error:] + 428
	4   CoreFoundation                      0x000000010efeedec __invoking___ + 140
	5   CoreFoundation                      0x000000010efeec42 -[NSInvocation invoke] + 290
	6   treevApp                            0x000000010c6e8555 -[GTMOAuth2SignIn invokeFinalCallbackWithError:] + 357
	7   treevApp                            0x000000010c6e6f1f -[GTMOAuth2SignIn windowWasClosed] + 111
	8   treevApp                            0x000000010c6ec041 -[GTMOAuth2ViewControllerTouch viewWillDisappear:] + 193
	9   UIKit                               0x000000010d2f2ffa -[UIViewController _setViewAppearState:isAnimating:] + 640
	10  UIKit                               0x000000010d31b132 -[UINavigationController viewWillDisappear:] + 113
	11  UIKit                               0x000000010d2f2ffa -[UIViewController _setViewAppearState:isAnimating:] + 640
	12  UIKit                               0x000000010d2cc480 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 445
	13  UIKit                               0x000000010d1e25ec _applyBlockToCFArrayCopiedToStack + 314
	14  UIKit                               0x000000010d1e2466 _afterCACommitHandler + 533
	15  CoreFoundation                      0x000000010f02bca7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	16  CoreFoundation                      0x000000010f02bc00 __CFRunLoopDoObservers + 368
	17  CoreFoundation                      0x000000010f021a33 __CFRunLoopRun + 1123
	18  CoreFoundation                      0x000000010f021366 CFRunLoopRunSpecific + 470
	19  GraphicsServices                    0x0000000111007a3e GSEventRunModal + 161
	20  UIKit                               0x000000010d1be8c0 UIApplicationMain + 1282
	21  treevApp                            0x000000010c59dc17 main + 135
	22  libdyld.dylib                       0x00000001108eb145 start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

At least for me, it crashes everytime I tap on the back button.

**Comment by Ashish145** [comment]
@SzabZappDesigntemplates Yes i also got error something like this.

**Comment by sqrrrl** [comment]
See https://developers.google.com/identity/sign-in/ios/start-integrating for further instructions as well as support links for integrating Google Sign-In
