### ISSUE TITLE
Unable to find Client Secret in Google API console.

### ISSUE THREAD

**Issue by rajasajidmanzoor** [googledrive/ios-quickeditor#5]
Hello
I am unable to find Client Secret in Google API Console. I have following credentials in google API console.

![image](https://cloud.githubusercontent.com/assets/5917783/17402623/9cbc6794-5a6d-11e6-89c2-6ae7299aa57b.png)

Please tell me where can i find ClientSecret for my App.

Thanks

**Comment by sajiddesigner** [comment]
@sqrrrl  @aliafshar @erickoledadevrel @naokirodion @DrChrispoper Friends any update.
I am still waiting for your reply..

Sajid

**Comment by vemulanishanth** [comment]
source: https://developers.google.com/drive/ios/quickstart?ver=swift
There is no need for Client Secret.
After I downloaded the project and run it (everything worked fine), I created a text file.
When I tried the application with my credentials without any other changes in the project, list of files is empty.

**Comment by sqrrrl** [comment]
Updating to new Google Sign-in with PR #12. Instructions updated as part of that change.
