### ISSUE TITLE
Getting an error "disallowed_useragent"

### ISSUE THREAD

**Issue by harshchitrla** [googledrive/ios-quickeditor#7]
I have changed the client-Id, Client-secret . I'm gettint the following error.
This user--agent is not permitted to make an OAuth authorization request to Google as it is classfied  as an embedded user agent (also known as web-view.). Per our policy, only browsers are permitted to make authorization request to Google

**Comment by LewisLebentz** [comment]
I have the same issue, here is a screenshot:

![screen shot 2016-12-29 at 15 02 38](https://cloud.githubusercontent.com/assets/5428939/21546627/f1638966-cdd7-11e6-845d-ab28d78bc3ec.png)

**Comment by harshchitrla** [comment]
Can you open the url below and  follow the steps , it worked for me

[https://developers.google.com/identity/sign-in/ios/start-integrating](url)

**Comment by sqrrrl** [comment]
Have a PR (#12) to fix this.
